### ISSUE TITLE
After installing extension cannot open password settings in MS EDGE Linux

### ISSUE THREAD

**Issue by ChrisNewbie** [keepassxreboot/keepassxc-browser#1371]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After installing KeepassXC cannot open password settings in MS EDGE Linux

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install MS EDGE Linux
2. Install KeepassXC
3. try to open edge://settings/passwords

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I can open edge://settings/passwords after install KeePassXC

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
White screen in Edge Browser

## Context
[NOTE]: # ( Give us any additional information you may have. )
From Edge F12 Console
TypeError: Cannot read property 'value' of undefined
    at cf.renderTableSubLabel (settings.bundle.js:1)
    at cf.render (settings.bundle.js:1)
    at Ha (lib_react.chunk.js:9)
    at Ua (lib_react.chunk.js:9)
    at ku (lib_react.chunk.js:9)
    at ml (lib_react.chunk.js:9)
    at vl (lib_react.chunk.js:9)
    at ul (lib_react.chunk.js:9)
    at lib_react.chunk.js:9
    at t.unstable_runWithPriority (lib_common.chunk.js:38)
    at Bi (lib_react.chunk.js:9)
    at Yi (lib_react.chunk.js:9)
    at qi (lib_react.chunk.js:9)
    at ll (lib_react.chunk.js:9)
    at Object.notify (lib_react.chunk.js:17)
    at e.t.notifyNestedSubs (lib_react.chunk.js:17)
    at e.t.handleChangeWrapper (lib_react.chunk.js:17)
    at g (lib_react.chunk.js:25)
    at Object.dispatch (lib_react.chunk.js:25)
    at kB (settings.bundle.js:1)
iu @ lib_react.chunk.js:9
passwords:1 Error in event handler: TypeError: Cannot read property 'value' of undefined
    at cf.renderTableSubLabel (edge://settings/settings.bundle.js:1:1172195)
    at cf.render (edge://settings/settings.bundle.js:1:1186557)
    at Ha (edge://settings/lib_react.chunk.js:9:70074)
    at Ua (edge://settings/lib_react.chunk.js:9:69869)
    at ku (edge://settings/lib_react.chunk.js:9:105483)
    at ml (edge://settings/lib_react.chunk.js:9:96924)
    at vl (edge://settings/lib_react.chunk.js:9:96849)
    at ul (edge://settings/lib_react.chunk.js:9:93879)
    at edge://settings/lib_react.chunk.js:9:45520
    at t.unstable_runWithPriority (edge://settings/lib_common.chunk.js:38:3844)
    at Bi (edge://settings/lib_react.chunk.js:9:45229)
    at Yi (edge://settings/lib_react.chunk.js:9:45465)
    at qi (edge://settings/lib_react.chunk.js:9:45400)
    at ll (edge://settings/lib_react.chunk.js:9:94170)
    at Object.notify (edge://settings/lib_react.chunk.js:17:3692)
    at e.t.notifyNestedSubs (edge://settings/lib_react.chunk.js:17:3266)
    at e.t.handleChangeWrapper (edge://settings/lib_react.chunk.js:17:3334)
    at g (edge://settings/lib_react.chunk.js:25:8916)
    at Object.dispatch (edge://settings/lib_react.chunk.js:25:6386)
    at kB (edge://settings/settings.bundle.js:1:2428247)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 20.04.2
Desktop Env: Gnome
Windowing System: X1
Microsoft Edge Wersja 92.0.902.45 (Oficjalna kompilacja) beta (wersja 64-bitowa)

**Comment by droidmonkey** [comment]
That's ironic. I'd also say this is a bug in the edge browser and perhaps a security bug on their part since am extension can interfere with the built in pages.

**Comment by varjolintu** [comment]
On macOS that page opens just fine.

**Comment by ChrisNewbie** [comment]
> That's ironic. I'd also say this is a bug in the edge browser and perhaps a security bug on their part since am extension can interfere with the built in pages.

Unfortuntely uninstalling extension didnt resolve the problem :/
